### ISSUE TITLE
RFC: Updates to Babel Plugin for modularity story

### ISSUE THREAD

**Issue by DrewML** [magento-research/pwa-buildpack#13]
Proposing the following changes to the current functionality:

- Instead of an `mid` prop, we switch to `data-mid` (or another `data-*`), and make the requirement that an element can only become a container if it is a DOM element with 0 hard-coded children. Example
	```jsx
	// ok
	<div data-mid='product.page.pricing' />

   // not ok
   <Foo data-mid='product.page.pricing' />
   // not ok
   <div data-mid='product.page.pricing'>Some Children</div>
	```
	The motivations for this change are:
		- `data-*` and only DOM elements to prevent collisions with TypeScript/Flow, and any future tooling that dislikes unrecognized props
		- No children because we want to support injection and re-ordering of children (parity with a necessary feature of current-state Magento). Allowing untargetable code nested in the children (arbitrary expressions) makes things less predictable for module devs

- Add support for ordering of contents injected into a container.
	- Leaving how this will be done open for now. Needs some exploration

**Comment by jimbo** [comment]
> Re-reading - are you looking for indexed access, or are you just looking for prepend/append, that adds in the first/last slots in a container, regardless of what other children are present?

If you think of a list of children as an array, and if we're going to offer `insert` operations, it's clear why we might want `insertAt(index)` in addition to `insertBefore(key)`. But since we're going to be doing reordering at the presentation layer, it doesn't really matter. It would probably be good enough to say that `insertBefore` without a target acts as "insert before everything" (and equivalent for `insertAfter`).
